### ISSUE TITLE
single energy calculation from FFT Hamiltonian  not implemented for Monte Carlo

### ISSUE THREAD

**Issue by loudesplat** [bertdupe/Matjes#73]
The `energy_single` subroutine in /src/Hamiltonian_type/hamiltonian_collection.f90:385 is currently missing a subroutine to calculate the local energy for the FFT Hamiltonian. That would be an equivalent of 
`this%H(iH)%eval_single(order)%calc(this%H(iH),tmp_E(iH),i_m,lat,work)`
for H_fft.

**Comment by patrick432** [comment]
I tried implementing this and remembered the reason I did not finish this the last time.

While all parts are essentially there one has the same problem as in the non-FFT Hamiltonian case with double counting.
The issue is that one wants to know all energy contributions caused by a single site. 

In the non-FFT case this is done by the vector-matrix-vector product with the entire magnetization, the Hamiltonian, and the magnetization of the considered site. For non-diagonal terms one needs another factor 2 because of the reverse, but not for the diagonal (anisotropy) terms. (And a factor 4 for 4-spin interactions)
So far this is solved rather bluntly with saving the multiplicative factor explicitly for each Hamiltonian and multiplying this manually. 

In case of the FFT-Hamiltonians one has the same problem, however for the DDI there are onsite and neighboring terms in the same Hamiltonian naturally. 
I guess there are several ways to address this.
One possibilty would be to take out all on-site term and adding them for example to an non-FFT Hamiltonian (which showes how non-sensical the FFT version of the anisotropy is in that case.
Alternatively one could look into the FFT formalism to find out if it is always clear which kernel terms are the onsite terms (I am not sure if that is possible). 

However, since the single site FFT evaluation is extremely slow at the moment anyways, I might make more sense to start this at a lower level. Right now the lazy and slow implementation calculates all effective field (doing 2 full FFTs) and takes only the one at the considered site. There is probably a faster way to get the energy caused by one moment in an FFT-Hamiltonian, but one would have to look into that more seriously.

**Comment by bertdupe** [comment]
Hello,
I will have a look. I am getting into the code more and more and it is quite cool actually :)

**Comment by bertdupe** [comment]
I see...
so the problem is that you have a special type of Ham for the FFT and it is not combined with the other Hamiltonian right? FFT_H is not a derived type of t_H.

**Comment by patrick432** [comment]
That is the case, yes.
The reason for that is that in Fortran an allocatable class array can constist only of one derived type (ie. you can not use Eigen and MKL at the same time). As the FFT Hamiltonians are rather different I put them into a separate array in the "hamiltonian" type.

This is not really a problem though, extention to include the single energy for the FTT-hamiltonian is easy on that level as the interface is already implemented, the problem is rather that the current implementation is very slow and incorrect for onsite terms as described  above.

**Comment by bertdupe** [comment]
sure I have seen that you have created a type containing the FFT Hamiltonian so I think I will be able to find a work around. I still do not understand the slowdown problem that you are mentioning but I guess I will find out :))

**Comment by patrick432** [comment]
For the slowdown you have to actually the single energy with fft adding something like

    do iH=1,this%NHF_local
        Call this%H_fft(ih)%get_E_single(lat,i_m,tmp_E(iH+this%NH_local))
    enddo

to energy_single in hamiltonian_collection.f90
You will see that it gets VERY slow compared to the version without FFT.

**Comment by bertdupe** [comment]
ohhhhhhhhh my God!!! 36 times slower...
This is slooooooooowwwwww

**Comment by bertdupe** [comment]
without the FFT, the slow down is 82 times

**Comment by bertdupe** [comment]
the dipole FFT is coded but slow. I am working on the speed up
